# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transactiontype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transactionType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.TransactionType'),
        ),
    ]
