# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_transaction_transactiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='manager',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
