# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20170307_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'ordering': ['factor']},
        ),
        migrations.AddField(
            model_name='broker',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.Investor'),
        ),
    ]
