# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20170308_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transactionDate', 'broker', 'bond']},
        ),
    ]
