# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maturity', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BondType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=10)),
                ('prefixed', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='bond',
            name='bondtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bonds.BondType'),
        ),
    ]
