# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondtype',
            name='hasCoupon',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
