# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0002_bondtype_hascoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondtype',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
