# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0003_auto_20170307_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='latestPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bond',
            name='latestPriceDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
