# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0004_auto_20170307_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bond',
            options={'ordering': ['bondtype', 'maturity']},
        ),
    ]
