# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonds', '0005_auto_20170307_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bondtype',
            options={'ordering': ['code']},
        ),
    ]
